"use strict";

// Rendering the crew: one agent definition file per role, shaped by the mode.
//
// The tool list is an allowlist rather than a denylist because the allowlist is
// the form the 2026-09-15 feasibility spike actually exercised. `skills:` is
// capped at two entries because the documentation is explicit that it injects
// the full skill text and not the description, so a generous list would spend a
// worker's context before it reaches its brief.
//
// A role left with no tools renders nothing at all. An agent definition with
// an empty tool list is not a harmless no-op: it is a worker that can be
// dispatched and can do nothing, which reads to the dispatcher as a broken crew
// rather than as a mode that withheld a role on purpose.

const fs = require("fs");
const path = require("path");

const MAX_SKILLS = 2;

const GENERATED =
  "<!-- Generated by `ccfg mode`. Edit the role in modes/roles/, not this file. -->";

/**
 * The roles a mode puts to work. A mode that runs alone gets none:
 * hooks/mode-guard.js already denies the Agent and Task tools in that posture,
 * so agent files would be definitions for workers nothing can dispatch.
 */
function crewRoster(roles, subagents) {
  return subagents === "none" ? [] : roles;
}

function allowedTools(role, deniedTools) {
  return role.tools.filter((tool) => !deniedTools.includes(tool));
}

function renderAgent(role, resolvedSettings, deniedTools, briefBand) {
  const tools = allowedTools(role, deniedTools);
  if (tools.length === 0) return null;

  const skills = role.skills.slice(0, MAX_SKILLS);
  const header = [
    "---",
    `name: ${role.id}`,
    `description: ${role.description}`,
    `tools: ${tools.join(", ")}`,
  ];
  if (skills.length > 0) header.push(`skills: ${skills.join(", ")}`);
  header.push("---");

  const posture = Object.entries(resolvedSettings)
    .map(([name, value]) => `${name}: ${value}`)
    .join(", ");

  const sections = [
    header.join("\n"),
    GENERATED,
    `<!-- mode posture: ${posture} -->`,
    role.body,
  ];
  if (briefBand.trim().length > 0) sections.push(briefBand.trim());

  return sections.join("\n\n").trimEnd() + "\n";
}

/** Whether a file in agents/ was written by this renderer. */
function isGenerated(file) {
  try {
    return fs.readFileSync(file, "utf8").includes(GENERATED);
  } catch {
    return false;
  }
}

/**
 * Write the whole crew, and remove the agent files a previous mode wrote that
 * this one does not.
 *
 * Ownership is decided by the generated marker, never by name: a file in
 * agents/ that this renderer did not write is the operator's own, and is
 * neither removed nor overwritten, even when it carries a role's name.
 */
function writeCrew(configDir, roles, resolvedSettings, deniedTools, briefBand) {
  const directory = path.join(configDir, "agents");

  const written = [];
  const keep = new Set();
  for (const role of roles) {
    const text = renderAgent(role, resolvedSettings, deniedTools, briefBand);
    if (text === null) continue;
    const destination = path.join(directory, `${role.id}.md`);
    if (fs.existsSync(destination) && !isGenerated(destination)) continue;
    fs.mkdirSync(directory, { recursive: true });
    fs.writeFileSync(destination, text);
    written.push(destination);
    keep.add(`${role.id}.md`);
  }

  if (!fs.existsSync(directory)) return written;
  for (const entry of fs.readdirSync(directory)) {
    if (!entry.endsWith(".md") || keep.has(entry)) continue;
    const file = path.join(directory, entry);
    if (isGenerated(file)) fs.rmSync(file, { force: true });
  }

  return written;
}

module.exports = {
  crewRoster,
  allowedTools,
  renderAgent,
  isGenerated,
  writeCrew,
  GENERATED,
};
