"use strict";

// Ordering, not selection.
//
// 1,218 measured trials say position governs adherence and length does not: the
// same rule hoisted to the top of a 211-line prompt beat the same rule buried at
// line 145 by 26 percentage points, and matched a 22-line prompt containing
// nothing else. Burial was worse than absence for at least one rule.
//
// So a mode re-sorts the corpus and never removes from it. Nothing is dropped,
// which means a mode cannot quietly disable a guardrail -- the failure that
// would make this whole system a liability.

const settings = require("./settings.js");

/**
 * Split the corpus into the band the active posture makes primary and the rest.
 *
 * A rule whose setting the mode never resolved falls to standing rather than
 * disappearing, so an unrecognised setting name costs position and not the rule.
 */
function band(corpusRules, resolvedSettings) {
  const primary = [];
  const standing = [];

  for (const rule of corpusRules) {
    const active = resolvedSettings[rule.setting];
    let isPrimary = false;
    if (active !== undefined) {
      isPrimary =
        typeof rule.only_at === "string"
          ? active === rule.only_at
          : settings.atOrAbove(rule.setting, active, rule.primary_at);
    }
    if (isPrimary) primary.push(rule);
    else standing.push(rule);
  }

  return { primary, standing };
}

function section(title, bandRules) {
  if (bandRules.length === 0) return "";
  return `## ${title}\n\n${bandRules.map((rule) => rule.body).join("\n\n")}\n\n`;
}

function renderActive(corpusRules, resolvedSettings, modeName) {
  const { primary, standing } = band(corpusRules, resolvedSettings);
  const posture = Object.entries(resolvedSettings)
    .map(([name, value]) => `${name}: ${value}`)
    .join(", ");

  const rendered =
    "<!-- Generated by `ccfg mode`. Edit the rules in modes/rules/, not this file. -->\n" +
    `<!-- mode: ${modeName} -- ${posture} -->\n\n` +
    section("Rules for this mode", primary) +
    section("Standing rules", standing);

  return rendered.trimEnd() + "\n";
}

module.exports = { band, renderActive };
